#!/bin/sh

d=$RPM_BUILD_ROOT/usr/lib/perl5

[ -d $d ] || exit 0


find $d -name ".packlist" | xargs rm -f

# remove file alike /usr/lib/perl5/5.8.*/i386-linux-thread-multi/perllocal.pod
perl -MConfig -e 'unlink "$ENV{RPM_BUILD_ROOT}$Config{installarchlib}/perllocal.pod"'

for i in $(find $d -name "*.bs"); do
    if [ -s $i ]; then
      echo "non empty *.bs file, please mail pixel@mandrakesoft.com about this!"
    else
      rm -f $i
    fi
done
