#!/bin/sh

if test -z "$DONT_FIX_PAMD_CONFIGS"; then
    configs=`find $RPM_BUILD_ROOT/etc/pam.d/ -type f ! -type l 2> /dev/null`
    if [ -n "$configs" ]; then
        echo -n "Fixing pam.d config files..."
        perl -pi -e "s,/(lib|lib64)/security/,," $configs
        echo "done"
    fi
fi

