#!/usr/bin/perl
# -*- Mode: cperl -*-
# Copyright (C) 2000 by Chmouel Boudjnah <chmouel@mandrakesoft.com>
# Redistribution of this file is permitted under the terms of the GNU 
# Public License (GPL)
## description: Convert full link to relative links.

my $r=$ENV{RPM_BUILD_ROOT};
chdir($r) or die "Can't cd to $ENV{RPM_BUILD_ROOT}: $!";

push my @files, split(/\n/, `find -type l 2> /dev/null`);
foreach my $file (@files) {
    my $link = readlink($file);
    if ($link =~ m!^/!) {
	$link =~ s|^/||;
	# Ugly ? no simply chmou.
	(my $dirname = $file) =~ s|/[^/]*$||; $dirname =~ s|/[^/]+|../|g; $dirname =~ s|^\.||;
      	system("ln -sf $dirname$link $file");
    }
}
