#!/bin/sh
# $Id$

if [ -z "$RPM_BUILD_ROOT" ]; then
    echo "No build root defined" >&2
    exit 1
fi

if [ ! -d "$RPM_BUILD_ROOT" ]; then
    echo "Invalid build root" >&2
    exit 1
fi

INFODIR=`rpm --eval %{_infodir}/dir`

dir="$RPM_BUILD_ROOT/$INFODIR"

if [ -f $dir -a ! -L $dir ]; then
    rm -f $dir 
fi

